#define scm_from_sp_sample(a) scm_from_double(a)
#define scm_to_sp_sample(a) scm_to_double(a)
#define scm_c_make_sp_samples(len) scm_make_f64vector((scm_from_sp_sample_count(len)), (scm_from_uint8(0)))
#define scm_c_take_samples(a, len) scm_take_f64vector(a, len)
#define scm_c_take_sample_counts(a, len) scm_take_u32vector(a, len)
#define scm_from_sp_channel_count(a) scm_from_uint8(a)
#define scm_from_sp_sample_rate(a) scm_from_uint32(a)
#define scm_from_sp_sample_count(a) scm_from_uint32(a)
#define scm_from_sp_float(a) scm_from_double(a)
#define scm_to_sp_channel_count(a) scm_to_uint8(a)
#define scm_to_sp_fm_synth_count(a) scm_to_uint8(a)
#define scm_to_sp_asynth_count(a) scm_to_uint16(a)
#define scm_to_sp_sample_rate(a) scm_to_uint32(a)
#define scm_to_sp_sample_count(a) scm_to_uint32(a)
#define scm_to_sp_float(a) scm_to_double(a)
