#!/bin/sh
echo "## (sph sp)"
echo "~~~"
scm-list-documentation "sph sp"
echo "~~~"
echo
echo "## (sph sp synthesise)"
echo "sequencing and sound synthesis with composable sequencer objects"
echo "~~~"
scm-list-documentation "sph sp synthesise"
echo "~~~"
echo
echo "## (sph sp vectorise)"
echo "~~~"
scm-list-documentation "sph sp vectorise"
echo "~~~"
